name: Lint the Fortran code and the MEX gateways on GitHub hosted runners

on:
  # Trigger the workflow on push or pull request
  push:
  #pull_request:  # DANGEROUS! MUST be disabled for self-hosted runners!
  # Trigger the workflow by cron. The default time zone of GitHub Actions is UTC.
  schedule:
    - cron: '0 17 * * *'
  # Trigger the workflow manually
  workflow_dispatch:


jobs:

  test:
    name: Lint the Fortran code and the MEX gateways
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        linter: [flint]
        solver: [newuoa, cobyla, lincoa, bobyqa, uobyqa]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.2
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY_ACT }} # This forces checkout to use SSH, not HTTPS
          submodules: recursive

      - name: Miscellaneous setup
        run: bash .github/scripts/misc_setup

      - name: Install gfortran
        uses: awvwgk/setup-fortran@main
        id: setup-fortran
        with:
          compiler: gcc

      - name: Install Intel oneAPI
        run: bash .github/scripts/install_oneapi_linux.sh

      - name: Install AOCC
        run: bash .github/scripts/install_aocc

      - name: Install Flang
        run: bash .github/scripts/install_flang

      - name: Install g95
        run: bash .github/scripts/install_g95

      - name: Install nvfortran
        run: bash .github/scripts/install_nvfortran

      - name: Install Oracle sunf95
        run: bash .github/scripts/install_sunf95

      - name: Conduct the test
        run: |
          cd "$ROOT_DIR"/fortran/${{ matrix.solver }} && bash ./${{ matrix.linter }} --all
